CREATE DATABASE IF NOT EXISTS waffles;
USE waffles;

DROP TABLE IF EXISTS Users;
CREATE TABLE Users (
  Id INT PRIMARY KEY AUTO_INCREMENT,
  Email VARCHAR(255) NOT NULL,
  Password VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS ToDos;
CREATE TABLE ToDos (
  Id INT PRIMARY KEY AUTO_INCREMENT,
  Title VARCHAR(255) NOT NULL,
  Description VARCHAR(255),
  State VARCHAR(255),
  UserID INT FOREIGN KEY REFERENCES Users(Id)
);

DROP TABLE IF EXISTS Boards;
CREATE TABLE Boards (
  Id INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(255) NOT NULL,
  UserID INT FOREIGN KEY REFERENCES Users(Id),
);

DROP TABLE IF EXISTS BoardsToDos;
CREATE TABLE BoardsToDos (
  BoardID INT FOREIGN KEY REFERENCES Boards(Id),
  ToDosID INT FOREIGN KEY REFERENCES ToDos(Id)
);
