
DROP TABLE IF EXISTS Users;
CREATE TABLE Users (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Email VARCHAR(255) NOT NULL,
  Password VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS ToDos;
CREATE TABLE ToDos (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Title VARCHAR(255) NOT NULL,
  Description VARCHAR(255),
  State VARCHAR(255),
  UserID INTEGER NOT NULL,
  FOREIGN KEY (UserID) REFERENCES Users (Id)
);

DROP TABLE IF EXISTS Boards;
CREATE TABLE Boards (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Name VARCHAR(255) NOT NULL,
  UserID INTEGER NOT NULL,
  FOREIGN KEY (UserID) REFERENCES Users (Id)
);

DROP TABLE IF EXISTS BoardsToDos;
CREATE TABLE BoardsToDos (
  BoardID INTEGER NOT NULL,
  ToDosID INTEGER NOT NULL,
  FOREIGN KEY (ToDosID) REFERENCES ToDos (Id)
  FOREIGN KEY (BoardID) REFERENCES Boards (Id)
);
